# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sprockets_helper_rails3}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Katz"]
  s.date = %q{2011-10-29}
  s.description = %q{A helper gem that attaches fingerprint for static assets (js/css) using sprockets in rails 3.0}
  s.email = %q{ilyakatz@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/initializers/sprockets_helper.rb",
    "lib/sprockets_helper_rails3.rb",
    "spec/helpers/assets_helper_spec.rb",
    "spec/spec_helper.rb",
    "sprockets_helper_rails3.gemspec",
    "test/rails_app/app/assets/javascripts/application.js",
    "test/rails_app/app/assets/stylesheets/application.css",
    "test/rails_app/config/application.rb",
    "test/rails_app/config/boot.rb",
    "test/rails_app/config/environment.rb",
    "test/rails_app/config/routes.rb",
    "test/rails_app/public/javascripts/application.js",
    "test/rails_app/public/javascripts/controls.js",
    "test/rails_app/public/javascripts/dragdrop.js",
    "test/rails_app/public/javascripts/effects.js",
    "test/rails_app/public/javascripts/prototype.js",
    "test/rails_app/public/javascripts/rails.js",
    "test/rails_app/public/stylesheets/.gitkeep"
  ]
  s.homepage = %q{http://github.com/ilyakatz/sprockets_helper_rails3}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Sprockets helper for rails3.0}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sprockets>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<actionpack>, ["~> 3.0.10"])
      s.add_development_dependency(%q<rails>, ["~> 3.0.10"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sprockets>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<actionpack>, ["~> 3.0.10"])
      s.add_dependency(%q<rails>, ["~> 3.0.10"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sprockets>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<actionpack>, ["~> 3.0.10"])
    s.add_dependency(%q<rails>, ["~> 3.0.10"])
  end
end

